apiVersion: v1
kind: Service
metadata:
  name: chat-ting-server-db         # ✅ 서비스명은 그대로 유지
  labels:
    app: chat-ting-server-db
spec:
  type: ClusterIP
  selector:
    app: chat-ting-server-db
  ports:
    - port: 5432
      targetPort: 5432
