apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ting-server-db
  labels:
    app: chat-ting-server-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ting-server-db
  template:
    metadata:
      labels:
        app: chat-ting-server-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.db }}       # ✅ 여기 → chat-ting-server-db
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-ting-server-db-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: init-sql
              subPath: init.sql
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: chat-ting-server-db-pvc
        - name: init-sql
          configMap:
            name: chat-ting-db-init