# application-common.yml
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
