spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chat_ting
    username: postgres
    password: qwer1234
    pool:
      enabled: true
      max-size: 100  # ← 최소 100 이상으로 설정 권장
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.r2dbc.core: debug
    io.r2dbc.postgresql.QUERY: debug
    io.r2dbc.postgresql.PARAM: trace

auth:
  token-ttl-minutes: 60