spring:
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC ????? ?????.
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?serverTimezone=UTC
    platform: postgres # ???? ?????? ???? ?????.
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.hibernate.SQL: warn
auth:
  token-ttl-minutes: ${TOKEN_TTL_MINUTES}