spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.hibernate.SQL: info
auth:
  token-ttl-minutes: ${TOKEN_TTL_MINUTES}