spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
logging:
  level:
    org.hibernate.SQL: warn
auth:
  token-ttl-minutes: ${TOKEN_TTL_MINUTES}