# application-common.yml
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  security:
    enabled: false  # ✅ actuator 보안 비활성화